# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:38:58+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class FieldAddressGetResponse(BaseModel):
    description: Optional[str] = None
    trap: Optional[bool] = None
